name: Django-app workflow

on: [push]

jobs:

  copy_files_to_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy infra files
        uses: garygrossgarten/github-action-scp@release
        with:
            local: ./infra/
            remote: /${{ secrets.USER }}/
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            privateKey: ${{ secrets.PASSPHRASE }}
